---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
devtools::load_all()
library(dplyr)
```

# elections: MEDSL data in R

This is an R package for accessing data on U.S. elections from the [MIT Election Data and Science Lab](https://electionlab.mit.edu).


## Installation

Install from GitHub:

```{r, eval = FALSE}
if (!require('devtools', quietly = TRUE)) install.packages('devtools')
devtools::install_github('MEDSL/elections')
```

## Use

```{r, result = 'hide', message = FALSE, eval = FALSE}
library(elections)
# We'll use dplyr for ease of illustration below
library(dplyr)
```

The package makes available the following datasets:

* [`presidential_precincts_2016`](http://dx.doi.org/10.7910/DVN/LYWX3D)
* [`senate_precincts_2016`](http://dx.doi.org/10.7910/DVN/NLTQAD)
* [`house_precincts_2016`](http://dx.doi.org/10.7910/DVN/PSKDUJ)
* [`state_precincts_2016`](http://dx.doi.org/10.7910/DVN/GSZG1O)
* [`local_precincts_2016`](http://dx.doi.org/10.7910/DVN/Q8OHRS)
* `state_ids`

```{r}
presidential_precincts_2016 %>%
  select(state_postal, county_fips, precinct, candidate, party, votes)
```

```{r}
senate_precincts_2016 %>%
  select(state_postal, county_fips, precinct, candidate, party, votes)
```

```{r}
house_precincts_2016 %>%
  select(state_postal, county_fips, precinct, candidate, party, votes)
```

```{r}
state_precincts_2016 %>%
  select(state_postal, county_fips, precinct, candidate, party, votes)
```

```{r}
local_precincts_2016 %>%
  select(state_postal, county_fips, precinct, candidate, party, votes)
```

State identifiers:

```{r}
head(state_ids)
```
